### PR TITLE
Updated Italian translation

### PR DESCRIPTION
**Pull request by ciampix**
Updated Italian translation

### CODE REVIEW

**Comment by bexelbie** [comment]
@mquinson ditto here re: guide mentioned in weblate update PR (other repo)

**Comment by ciampix** [comment]
sorry I do not understand you @bexelbie ... what do you mean?

**Comment by bexelbie** [comment]
@ciampix sorry was pointing @mquinson at my comment on https://github.com/mquinson/po4a/pull/79

We should have a maintainers checklist to ensure that everyone who has commit rights manages translation updates the exact same way.

**Comment by ciampix** [comment]
Just for the site translation purpose I can migrate to weblate if this simplify the translation workflow to all... btw I have _no_ commit rights on the web pages of po4a ... just on the po4a source repo (a bit weird...)

**Comment by mquinson** [comment]
Hello,

@ciampix I just granted you the commit right on both repo.

@bexelbie I usually push all changes as soon as I get something. I agree that it's a good idea to add a mention about it in the README file. Please be my guest :) I'll do it later this week if you dont beat me on this.

**Comment by ciampix** [comment]
@mquinson many thanks!
Re-reading my post found it a bit obscure. What I was trying to say (in a way a bit clumsy I may say...) is that my translation was accepted asking for a pull so it is possible to commit without having commit rights at all; that is probably another possible work-flow and it could also be safe to do it in this way if we manage to put in use a CI system to check for consistency of the po files before merging them... never did it myself but I know for sure that github supports it.

**Comment by bexelbie** [comment]
Following up on what @ciampix said, it would be ideal to have a PR based workflow if we can do CI testing on things like po files and then potentially auto-merge or bot-merge them.

I know the CI system we are looking at will support this idea, but it won't be ready immediately.

**Pull request merged**
